apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsule-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: capsule-app
  template:
    metadata:
      labels:
        app: capsule-app
    spec:
      containers:
      - name: capsule-app
        image: lijazs/retail-devops-project:v1.0.0
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: capsule-config
---
apiVersion: v1
kind: Service
metadata:
  name: capsule-service
spec:
  selector:
    app: capsule-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer